version: '3'

services:
 db-projeto:
  container_name: db-projeto 
  image: mysql:8.0
  restart: always
  ports:
   - '3306:3306'
  environment:
   - MYSQL_ROOT_PASSWORD=master
   - MYSQL_DATABASE=dbprojeto
   - MYSQL_USER=admin
   - MYSQL_PASSWORD=admin

 phpmyadmin:
  container_name: myadmin
  image: phpmyadmin
  restart: always
  ports:
  - 8080:80
  environment:
  - PMA_ARBITRARY=1

 apache:
  build: .
  container_name: apache
  restart: always
  ports:
  - '80:80'
  volumes:
  - ./src:/var/www/html:rw
  depends_on:
  - db-projeto
  links:
  - db-projeto
